version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  frontend:
    build:
      context: ./pep-checker-frontend
    ports:
      - "3000:3000"
